//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.AreaCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tools.AreaCalculator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string ButtonCalculateName {
            get {
                return ResourceManager.GetString("ButtonCalculateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteName {
            get {
                return ResourceManager.GetString("ButtonDeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSaveName {
            get {
                return ResourceManager.GetString("ButtonSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rooms.
        /// </summary>
        public static string LabelAllRooms {
            get {
                return ResourceManager.GetString("LabelAllRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Area.
        /// </summary>
        public static string LabelApartmentArea {
            get {
                return ResourceManager.GetString("LabelApartmentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Own.
        /// </summary>
        public static string LabelApartmentOwn {
            get {
                return ResourceManager.GetString("LabelApartmentOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Coefficient.
        /// </summary>
        public static string LabelAreaCoefficient {
            get {
                return ResourceManager.GetString("LabelAreaCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration Thickness.
        /// </summary>
        public static string LabelDecorationThickness {
            get {
                return ResourceManager.GetString("LabelDecorationThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Area Calculation.
        /// </summary>
        public static string LabelForAreaCalculation {
            get {
                return ResourceManager.GetString("LabelForAreaCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Count Calculation.
        /// </summary>
        public static string LabelForCountCalculation {
            get {
                return ResourceManager.GetString("LabelForCountCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Residential Area Calculation.
        /// </summary>
        public static string LabelForResidentialAreaCalculation {
            get {
                return ResourceManager.GetString("LabelForResidentialAreaCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of all rooms in model.
        /// </summary>
        public static string LabelNumberOfAllRoomsInModel {
            get {
                return ResourceManager.GetString("LabelNumberOfAllRoomsInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of correct rooms in model.
        /// </summary>
        public static string LabelNumberOfCorrectRoomsInModel {
            get {
                return ResourceManager.GetString("LabelNumberOfCorrectRoomsInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string LabelPurpose {
            get {
                return ResourceManager.GetString("LabelPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for calculation Rooms.
        /// </summary>
        public static string LabelRequiredRooms {
            get {
                return ResourceManager.GetString("LabelRequiredRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Apartment Area.
        /// </summary>
        public static string LabelResidentialApartmentArea {
            get {
                return ResourceManager.GetString("LabelResidentialApartmentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name.
        /// </summary>
        public static string LabelRoomName {
            get {
                return ResourceManager.GetString("LabelRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms Count.
        /// </summary>
        public static string LabelRoomsCount {
            get {
                return ResourceManager.GetString("LabelRoomsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Apartment Area.
        /// </summary>
        public static string LabelTotalApartmentArea {
            get {
                return ResourceManager.GetString("LabelTotalApartmentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For using this program you should do following preconditions for all rooms in Revit model.
        /// </summary>
        public static string TextInstruction {
            get {
                return ResourceManager.GetString("TextInstruction", resourceCulture);
            }
        }
    }
}
